ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

exclude: ^(Python/py3.10_errors/)

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-toml

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs

- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.2
  hooks:
  - id: markdown-toc

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black-jupyter

- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.18.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.1.0]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
  - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
