target-version = "py38"
exclude = ["*__init__.py"]
lint.ignore = [
    "E501",
    "F401", # unused import, deliberate
]
lint.select = [
    "E",
    "F",
    "W",
    "B",
    "I",
]

[lint.isort]
combine-as-imports = true
